# Recurrent Neural Network (RNN)

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Part 1 - Data Preprocessing

### Importing the dataset

In [2]:
dataset = pd.read_excel('Data.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)
print(y)
print(X.shape)
print(y.shape)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  12.07   39.99 1009.7    93.27]
 [  28.83   66.44 1008.47   77.49]
 [  19.94   44.9  1008.52   74.69]]
[463.26 444.37 488.56 ... 473.06 430.01 459.47]
(10000, 4)
(10000,)


### Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [5]:
print(X_train)
print(y_train)

[[  25.28   67.69 1009.05   68.54]
 [   7.95   41.26 1008.48   97.92]
 [  26.95   72.24 1011.16   73.14]
 ...
 [  12.8    41.16 1022.43   86.19]
 [  22.42   71.77 1005.5    90.62]
 [  32.32   67.9  1006.08   37.93]]
[445.34 480.6  435.65 ... 462.72 435.06 428.12]


##Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
print(y_train.reshape(-1,1))
print(y_test.reshape(-1,1))


[[445.34]
 [480.6 ]
 [435.65]
 ...
 [462.72]
 [435.06]
 [428.12]]
[[455.58]
 [436.21]
 [458.28]
 ...
 [465.89]
 [451.51]
 [467.39]]


In [8]:
sc1 = StandardScaler()
y_train = sc1.fit_transform(y_train.reshape(-1,1))


## Part 2 - Building the RNN

### Initializing the RNN

In [9]:
rnn = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [10]:
rnn.add(tf.keras.layers.SimpleRNN(units=70, return_sequences=True, input_shape=(4,1)))

### Adding the second hidden layer

In [11]:
rnn.add(tf.keras.layers.SimpleRNN(units=70, return_sequences=True))

# Adding the third hidden layer

In [12]:
rnn.add(tf.keras.layers.SimpleRNN(units=70, return_sequences=False))

### Adding the output layer

In [13]:
rnn.add(tf.keras.layers.Dense(1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [15]:
rnn.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [16]:
rnn.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 5s 9ms/step - loss: 0.5429
Epoch 2/100
250/250 [==============================] - 2s 10ms/step - loss: 0.5315
Epoch 3/100
250/250 [==============================] - 2s 7ms/step - loss: 0.5300
Epoch 4/100
250/250 [==============================] - 2s 6ms/step - loss: 0.5294
Epoch 5/100
250/250 [==============================] - 2s 6ms/step - loss: 0.5290
Epoch 6/100
250/250 [==============================] - 2s 6ms/step - loss: 0.5292
Epoch 7/100
250/250 [==============================] - 1s 6ms/step - loss: 0.5290
Epoch 8/100
250/250 [==============================] - 1s 6ms/step - loss: 0.5289
Epoch 9/100
250/250 [==============================] - 2s 6ms/step - loss: 0.5284
Epoch 10/100
250/250 [==============================] - 2s 9ms/step - loss: 0.5283
Epoch 11/100
250/250 [==============================] - 2s 9ms/step - loss: 0.5277
Epoch 12/100
250/250 [==============================] - 1s 6ms/step - loss: 0.5282
Epoch 13/100

### Predicting the results of the Test set

In [17]:
from sklearn.metrics import r2_score, mean_squared_error,mean_absolute_percentage_error
import math
y_pred = sc1.inverse_transform(rnn.predict(X_test))
np.set_printoptions(precision=2)

maxY=max(y_test)
minY=min(y_test)
a=maxY-minY


print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
print ("The R-Squared value is: "+str(r2_score(y_test, y_pred)))
print ("The Mean Squared Error value is: "+str(mean_squared_error(y_test, y_pred)))
print ("The Root Mean Squared Error value is: "+str(math.sqrt(mean_squared_error(y_test, y_pred))))
print ("The Normalize Root Mean Squared Error value is: "+str(math.sqrt(mean_squared_error(y_test, y_pred))/(a)*100))
print ("The Mean Absolute Error value is: "+str(mean_absolute_percentage_error(y_test, y_pred)*100))


63/63 [==============================] - 1s 3ms/step
[[456.72 455.58]
 [454.17 436.21]
 [456.87 458.28]
 ...
 [467.53 465.89]
 [454.17 451.51]
 [468.57 467.39]]
The R-Squared value is: 0.49479942994172066
The Mean Squared Error value is: 145.96725431585202
The Root Mean Squared Error value is: 12.081690871556514
The Normalize Root Mean Squared Error value is: 17.247238931558204
The Mean Absolute Error value is: 2.1347091829144
