# Multiple Linear Regression

Mounting a Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/RealEstateDataset.csv')
X = dataset.iloc[:, 1:7].values
y = dataset.iloc[:, -1].values
print(X)


[[2012.917     32.        84.87882   10.        24.98298  121.54024]
 [2012.917     19.5      306.5947     9.        24.98034  121.53951]
 [2013.583     13.3      561.9845     5.        24.98746  121.54391]
 ...
 [2013.25      18.8      390.9696     7.        24.97923  121.53986]
 [2013.         8.1      104.8101     5.        24.96674  121.54067]
 [2013.5        6.5       90.45606    9.        24.97433  121.5431 ]]


In [ ]:
print(y)

[ 37.9  42.2  47.3  54.8  43.1  32.1  40.3  46.7  18.8  22.1  41.4  58.1
  39.3  23.8  34.3  50.5  70.1  37.4  42.3  47.7  29.3  51.6  24.6  47.9
  38.8  27.   56.2  33.6  47.   57.1  22.1  25.   34.2  49.3  55.1  27.3
  22.9  25.3  47.7  46.2  15.9  18.2  34.7  34.1  53.9  38.3  42.   61.5
  13.4  13.2  44.2  20.7  27.   38.9  51.7  13.7  41.9  53.5  22.6  42.4
  21.3  63.2  27.7  55.   25.3  44.3  50.7  56.8  36.2  42.   59.   40.8
  36.3  20.   54.4  29.5  36.8  25.6  29.8  26.5  40.3  36.8  48.1  17.7
  43.7  50.8  27.   18.3  48.   25.3  45.4  43.2  21.8  16.1  41.   51.8
  59.5  34.6  51.   62.2  38.2  32.9  54.4  45.7  30.5  71.   47.1  26.6
  34.1  28.4  51.6  39.4  23.1   7.6  53.3  46.4  12.2  13.   30.6  59.6
  31.3  48.   32.5  45.5  57.4  48.6  62.9  55.   60.7  41.   37.5  30.7
  37.5  39.5  42.2  20.8  46.8  47.4  43.5  42.5  51.4  28.9  37.5  40.1
  28.4  45.5  52.2  43.2  45.1  39.7  48.5  44.7  28.9  40.9  20.7  15.6
  18.3  35.6  39.4  37.4  57.8  39.6  11.6  55.5  5

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Multiple Linear Regression model on the Training set

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

## Predicting the Test set results

In [ ]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[40.1  45.3 ]
 [12.84 14.4 ]
 [42.01 46.  ]
 [12.65 15.6 ]
 [42.44 50.2 ]
 [39.83 38.1 ]
 [40.56 48.5 ]
 [33.86 41.4 ]
 [49.37 51.6 ]
 [45.87 40.1 ]
 [45.86 42.  ]
 [40.65 42.4 ]
 [39.51 28.5 ]
 [40.05 39.1 ]
 [47.12 53.7 ]
 [38.14 36.8 ]
 [40.08 40.6 ]
 [41.13 55.2 ]
 [40.84 39.3 ]
 [42.38 44.3 ]
 [49.7  53.5 ]
 [31.08 25.3 ]
 [39.68 22.8 ]
 [45.53 51.7 ]
 [46.19 45.5 ]
 [43.43 34.4 ]
 [46.36 31.6 ]
 [26.21 25.9 ]
 [48.14 49.5 ]
 [21.54 24.7 ]
 [44.81 51.7 ]
 [34.94 29.7 ]
 [42.66 45.4 ]
 [38.37 50.5 ]
 [43.98 26.5 ]
 [32.28 30.1 ]
 [47.62 46.1 ]
 [39.77 28.9 ]
 [52.56 54.4 ]
 [ 7.46 15.  ]
 [52.54 44.9 ]
 [33.13 29.8 ]
 [34.22 23.6 ]
 [49.59 48.  ]
 [15.38 16.7 ]
 [43.36 40.9 ]
 [42.41 40.2 ]
 [13.   12.9 ]
 [33.99 21.3 ]
 [48.5  62.1 ]
 [53.67 63.9 ]
 [38.73 40.3 ]
 [47.74 42.2 ]
 [25.42 19.1 ]
 [30.69 28.4 ]
 [34.27 28.5 ]
 [48.91 60.7 ]
 [40.62 37.5 ]
 [43.46 39.3 ]
 [32.95 28.8 ]
 [43.85 42.3 ]
 [43.63 44.3 ]
 [39.55 42.6 ]
 [47.02 57.4 ]
 [36.84 42.2 ]
 [30.01 25.7 ]
 [ 9.66 13

## Evaluating the Model Performance

In [ ]:
from sklearn.metrics import r2_score, mean_squared_error,mean_absolute_percentage_error
import math
maxY=max(y_test)
minY=min(y_test)
a=maxY-minY
print(a)
print ("The R-Squared value is: "+str(r2_score(y_test, y_pred)))
print ("The Mean Squared Error value is: "+str(mean_squared_error(y_test, y_pred)))
print ("The Root Mean Squared Error value is: "+str(math.sqrt(mean_squared_error(y_test, y_pred))))
print ("The Normalize Root Mean Squared Error value is: "+str(math.sqrt(mean_squared_error(y_test, y_pred))/a*100))
print ("The Mean Absolute Error value is: "+str(mean_absolute_percentage_error(y_test, y_pred)*100))


65.39999999999999
The R-Squared value is: 0.6573242742218073
The Mean Squared Error value is: 59.522435319024204
The Root Mean Squared Error value is: 7.715078438941772
The Normalize Root Mean Squared Error value is: 11.796756022846749
The Mean Absolute Error value is: 16.96835291350557
