# Polynomial Regression

Mounting a Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/RealEstateDataset.csv')
X = dataset.iloc[:, 1:7].values
y = dataset.iloc[:, -1].values
print(X)

[[2012.92   32.     84.88   10.     24.98  121.54]
 [2012.92   19.5   306.59    9.     24.98  121.54]
 [2013.58   13.3   561.98    5.     24.99  121.54]
 ...
 [2013.25   18.8   390.97    7.     24.98  121.54]
 [2013.      8.1   104.81    5.     24.97  121.54]
 [2013.5     6.5    90.46    9.     24.97  121.54]]


In [ ]:
print(y)

[ 37.9  42.2  47.3  54.8  43.1  32.1  40.3  46.7  18.8  22.1  41.4  58.1
  39.3  23.8  34.3  50.5  70.1  37.4  42.3  47.7  29.3  51.6  24.6  47.9
  38.8  27.   56.2  33.6  47.   57.1  22.1  25.   34.2  49.3  55.1  27.3
  22.9  25.3  47.7  46.2  15.9  18.2  34.7  34.1  53.9  38.3  42.   61.5
  13.4  13.2  44.2  20.7  27.   38.9  51.7  13.7  41.9  53.5  22.6  42.4
  21.3  63.2  27.7  55.   25.3  44.3  50.7  56.8  36.2  42.   59.   40.8
  36.3  20.   54.4  29.5  36.8  25.6  29.8  26.5  40.3  36.8  48.1  17.7
  43.7  50.8  27.   18.3  48.   25.3  45.4  43.2  21.8  16.1  41.   51.8
  59.5  34.6  51.   62.2  38.2  32.9  54.4  45.7  30.5  71.   47.1  26.6
  34.1  28.4  51.6  39.4  23.1   7.6  53.3  46.4  12.2  13.   30.6  59.6
  31.3  48.   32.5  45.5  57.4  48.6  62.9  55.   60.7  41.   37.5  30.7
  37.5  39.5  42.2  20.8  46.8  47.4  43.5  42.5  51.4  28.9  37.5  40.1
  28.4  45.5  52.2  43.2  45.1  39.7  48.5  44.7  28.9  40.9  20.7  15.6
  18.3  35.6  39.4  37.4  57.8  39.6  11.6  55.5  5

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Polynomial Regression model on the Training set

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 3)
X_poly = poly_reg.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

LinearRegression()

## Predicting the Test set results

In [ ]:
y_pred = regressor.predict(poly_reg.transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[37.82 45.3 ]
 [11.43 14.4 ]
 [41.9  46.  ]
 [12.04 15.6 ]
 [54.47 50.2 ]
 [34.25 38.1 ]
 [44.76 48.5 ]
 [37.31 41.4 ]
 [49.85 51.6 ]
 [47.49 40.1 ]
 [44.25 42.  ]
 [34.55 42.4 ]
 [36.95 28.5 ]
 [43.32 39.1 ]
 [54.98 53.7 ]
 [48.67 36.8 ]
 [33.83 40.6 ]
 [45.29 55.2 ]
 [37.03 39.3 ]
 [42.4  44.3 ]
 [56.84 53.5 ]
 [27.54 25.3 ]
 [24.59 22.8 ]
 [50.28 51.7 ]
 [53.5  45.5 ]
 [40.69 34.4 ]
 [38.38 31.6 ]
 [27.18 25.9 ]
 [53.24 49.5 ]
 [18.96 24.7 ]
 [46.77 51.7 ]
 [25.33 29.7 ]
 [41.55 45.4 ]
 [48.42 50.5 ]
 [37.11 26.5 ]
 [26.24 30.1 ]
 [46.41 46.1 ]
 [31.25 28.9 ]
 [55.85 54.4 ]
 [54.45 15.  ]
 [58.15 44.9 ]
 [38.26 29.8 ]
 [24.41 23.6 ]
 [46.21 48.  ]
 [18.8  16.7 ]
 [42.14 40.9 ]
 [34.51 40.2 ]
 [16.47 12.9 ]
 [28.63 21.3 ]
 [48.24 62.1 ]
 [56.69 63.9 ]
 [33.65 40.3 ]
 [42.29 42.2 ]
 [16.76 19.1 ]
 [27.88 28.4 ]
 [35.93 28.5 ]
 [56.98 60.7 ]
 [38.85 37.5 ]
 [44.01 39.3 ]
 [26.33 28.8 ]
 [40.66 42.3 ]
 [48.79 44.3 ]
 [39.52 42.6 ]
 [50.3  57.4 ]
 [39.29 42.2 ]
 [23.34 25.7 ]
 [12.34 13

## Evaluating the Model Performance

In [ ]:
from sklearn.metrics import r2_score, mean_squared_error,mean_absolute_percentage_error
import math
maxY=max(y_test)
minY=min(y_test)
a=maxY-minY
print(a)
print ("The R-Squared value is: "+str(r2_score(y_test, y_pred)))
print ("The Mean Squared Error value is: "+str(mean_squared_error(y_test, y_pred)))
print ("The Root Mean Squared Error value is: "+str(math.sqrt(mean_squared_error(y_test, y_pred))))
print ("The Normalize Root Mean Squared Error value is: "+str(math.sqrt(mean_squared_error(y_test, y_pred))/a*100))
print ("The Mean Absolute Error value is: "+str(mean_absolute_percentage_error(y_test, y_pred)*100))

65.39999999999999
The R-Squared value is: 0.6579977654760951
The Mean Squared Error value is: 59.40545055294472
The Root Mean Squared Error value is: 7.7074931432304705
The Normalize Root Mean Squared Error value is: 11.785157711361578
The Mean Absolute Error value is: 16.449913265554564
