# Decision Tree Regression

## Importing the libraries

Mounting a Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/RealEstateDataset.csv')
X = dataset.iloc[:, 1:7].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[2012.92   32.     84.88   10.     24.98  121.54]
 [2012.92   19.5   306.59    9.     24.98  121.54]
 [2013.58   13.3   561.98    5.     24.99  121.54]
 ...
 [2013.25   18.8   390.97    7.     24.98  121.54]
 [2013.      8.1   104.81    5.     24.97  121.54]
 [2013.5     6.5    90.46    9.     24.97  121.54]]
[ 37.9  42.2  47.3  54.8  43.1  32.1  40.3  46.7  18.8  22.1  41.4  58.1
  39.3  23.8  34.3  50.5  70.1  37.4  42.3  47.7  29.3  51.6  24.6  47.9
  38.8  27.   56.2  33.6  47.   57.1  22.1  25.   34.2  49.3  55.1  27.3
  22.9  25.3  47.7  46.2  15.9  18.2  34.7  34.1  53.9  38.3  42.   61.5
  13.4  13.2  44.2  20.7  27.   38.9  51.7  13.7  41.9  53.5  22.6  42.4
  21.3  63.2  27.7  55.   25.3  44.3  50.7  56.8  36.2  42.   59.   40.8
  36.3  20.   54.4  29.5  36.8  25.6  29.8  26.5  40.3  36.8  48.1  17.7
  43.7  50.8  27.   18.3  48.   25.3  45.4  43.2  21.8  16.1  41.   51.8
  59.5  34.6  51.   62.2  38.2  32.9  54.4  45.7  30.5  71.   47.1  26.6
  34.1  28.4  51.6  39.4  23.1 

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Decision Tree Regression model on the Training set

In [ ]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

## Predicting the Test set results

In [ ]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[117.5   45.3 ]
 [ 13.4   14.4 ]
 [ 39.4   46.  ]
 [ 15.5   15.6 ]
 [ 29.3   50.2 ]
 [ 37.4   38.1 ]
 [ 41.    48.5 ]
 [ 34.6   41.4 ]
 [ 60.85  51.6 ]
 [ 40.6   40.1 ]
 [ 47.4   42.  ]
 [  7.6   42.4 ]
 [ 32.9   28.5 ]
 [ 41.5   39.1 ]
 [ 63.2   53.7 ]
 [ 61.5   36.8 ]
 [ 30.    40.6 ]
 [ 55.3   55.2 ]
 [ 42.3   39.3 ]
 [ 39.7   44.3 ]
 [ 50.    53.5 ]
 [ 28.9   25.3 ]
 [ 32.2   22.8 ]
 [ 55.    51.7 ]
 [ 58.8   45.5 ]
 [ 43.7   34.4 ]
 [ 42.    31.6 ]
 [ 20.7   25.9 ]
 [ 52.2   49.5 ]
 [ 22.    24.7 ]
 [ 33.6   51.7 ]
 [ 23.    29.7 ]
 [ 47.85  45.4 ]
 [ 47.3   50.5 ]
 [ 42.    26.5 ]
 [ 29.5   30.1 ]
 [ 48.2   46.1 ]
 [ 21.7   28.9 ]
 [ 61.9   54.4 ]
 [ 12.2   15.  ]
 [ 50.8   44.9 ]
 [ 34.2   29.8 ]
 [ 30.7   23.6 ]
 [ 37.9   48.  ]
 [ 13.4   16.7 ]
 [ 33.6   40.9 ]
 [ 37.5   40.2 ]
 [ 11.6   12.9 ]
 [ 23.1   21.3 ]
 [ 42.8   62.1 ]
 [ 60.85  63.9 ]
 [ 33.1   40.3 ]
 [ 49.3   42.2 ]
 [ 18.3   19.1 ]
 [ 28.9   28.4 ]
 [ 30.9   28.5 ]
 [ 55.    60.7 ]
 [ 35.5   37.5 ]
 [ 47.4   39.3

## Evaluating the Model Performance

In [ ]:
from sklearn.metrics import r2_score, mean_squared_error,mean_absolute_percentage_error
import math
maxY=max(y_test)
minY=min(y_test)
a=maxY-minY
print(a)
print ("The R-Squared value is: "+str(r2_score(y_test, y_pred)))
print ("The Mean Squared Error value is: "+str(mean_squared_error(y_test, y_pred)))
print ("The Root Mean Squared Error value is: "+str(math.sqrt(mean_squared_error(y_test, y_pred))))
print ("The Normalize Root Mean Squared Error value is: "+str(math.sqrt(mean_squared_error(y_test, y_pred))/a*100))
print ("The Mean Absolute Error value is: "+str(mean_absolute_percentage_error(y_test, y_pred)*100))

65.39999999999999
The R-Squared value is: 0.16425800123264644
The Mean Squared Error value is: 145.16756024096384
The Root Mean Squared Error value is: 12.048550130242386
The Normalize Root Mean Squared Error value is: 18.42285952636451
The Mean Absolute Error value is: 18.78562773664168
