# Support Vector Regression (SVR)

Mounting a Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/RealEstateDataset.csv')
X = dataset.iloc[:, 1:7].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[2012.917     32.        84.87882   10.        24.98298  121.54024]
 [2012.917     19.5      306.5947     9.        24.98034  121.53951]
 [2013.583     13.3      561.9845     5.        24.98746  121.54391]
 ...
 [2013.25      18.8      390.9696     7.        24.97923  121.53986]
 [2013.         8.1      104.8101     5.        24.96674  121.54067]
 [2013.5        6.5       90.45606    9.        24.97433  121.5431 ]]
[ 37.9  42.2  47.3  54.8  43.1  32.1  40.3  46.7  18.8  22.1  41.4  58.1
  39.3  23.8  34.3  50.5  70.1  37.4  42.3  47.7  29.3  51.6  24.6  47.9
  38.8  27.   56.2  33.6  47.   57.1  22.1  25.   34.2  49.3  55.1  27.3
  22.9  25.3  47.7  46.2  15.9  18.2  34.7  34.1  53.9  38.3  42.   61.5
  13.4  13.2  44.2  20.7  27.   38.9  51.7  13.7  41.9  53.5  22.6  42.4
  21.3  63.2  27.7  55.   25.3  44.3  50.7  56.8  36.2  42.   59.   40.8
  36.3  20.   54.4  29.5  36.8  25.6  29.8  26.5  40.3  36.8  48.1  17.7
  43.7  50.8  27.   18.3  48.   25.3  45.4  43.2  21.8  16.1  41.   5

In [ ]:
y = y.reshape(len(y),1)
print(y)

[[ 37.9]
 [ 42.2]
 [ 47.3]
 [ 54.8]
 [ 43.1]
 [ 32.1]
 [ 40.3]
 [ 46.7]
 [ 18.8]
 [ 22.1]
 [ 41.4]
 [ 58.1]
 [ 39.3]
 [ 23.8]
 [ 34.3]
 [ 50.5]
 [ 70.1]
 [ 37.4]
 [ 42.3]
 [ 47.7]
 [ 29.3]
 [ 51.6]
 [ 24.6]
 [ 47.9]
 [ 38.8]
 [ 27. ]
 [ 56.2]
 [ 33.6]
 [ 47. ]
 [ 57.1]
 [ 22.1]
 [ 25. ]
 [ 34.2]
 [ 49.3]
 [ 55.1]
 [ 27.3]
 [ 22.9]
 [ 25.3]
 [ 47.7]
 [ 46.2]
 [ 15.9]
 [ 18.2]
 [ 34.7]
 [ 34.1]
 [ 53.9]
 [ 38.3]
 [ 42. ]
 [ 61.5]
 [ 13.4]
 [ 13.2]
 [ 44.2]
 [ 20.7]
 [ 27. ]
 [ 38.9]
 [ 51.7]
 [ 13.7]
 [ 41.9]
 [ 53.5]
 [ 22.6]
 [ 42.4]
 [ 21.3]
 [ 63.2]
 [ 27.7]
 [ 55. ]
 [ 25.3]
 [ 44.3]
 [ 50.7]
 [ 56.8]
 [ 36.2]
 [ 42. ]
 [ 59. ]
 [ 40.8]
 [ 36.3]
 [ 20. ]
 [ 54.4]
 [ 29.5]
 [ 36.8]
 [ 25.6]
 [ 29.8]
 [ 26.5]
 [ 40.3]
 [ 36.8]
 [ 48.1]
 [ 17.7]
 [ 43.7]
 [ 50.8]
 [ 27. ]
 [ 18.3]
 [ 48. ]
 [ 25.3]
 [ 45.4]
 [ 43.2]
 [ 21.8]
 [ 16.1]
 [ 41. ]
 [ 51.8]
 [ 59.5]
 [ 34.6]
 [ 51. ]
 [ 62.2]
 [ 38.2]
 [ 32.9]
 [ 54.4]
 [ 45.7]
 [ 30.5]
 [ 71. ]
 [ 47.1]
 [ 26.6]
 [ 34.1]
 [ 28.4]
 [ 51.6]
 

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
y_train = sc_y.fit_transform(y_train)

## Training the SVR model on the Training set

In [ ]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

## Predicting the Test set results

In [ ]:
y_pred = sc_y.inverse_transform(regressor.predict(sc_X.transform(X_test)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),axis=1))

[[39.52 45.3 ]
 [15.67 14.4 ]
 [40.66 46.  ]
 [16.41 15.6 ]
 [43.77 50.2 ]
 [39.59 38.1 ]
 [41.19 48.5 ]
 [38.13 41.4 ]
 [53.79 51.6 ]
 [47.01 40.1 ]
 [47.14 42.  ]
 [37.31 42.4 ]
 [38.43 28.5 ]
 [41.16 39.1 ]
 [52.52 53.7 ]
 [39.64 36.8 ]
 [39.03 40.6 ]
 [40.89 55.2 ]
 [40.78 39.3 ]
 [40.72 44.3 ]
 [49.72 53.5 ]
 [23.87 25.3 ]
 [31.61 22.8 ]
 [47.57 51.7 ]
 [51.05 45.5 ]
 [44.8  34.4 ]
 [45.01 31.6 ]
 [21.19 25.9 ]
 [52.48 49.5 ]
 [23.8  24.7 ]
 [43.84 51.7 ]
 [29.24 29.7 ]
 [43.6  45.4 ]
 [39.68 50.5 ]
 [43.96 26.5 ]
 [26.34 30.1 ]
 [40.47 46.1 ]
 [31.24 28.9 ]
 [49.77 54.4 ]
 [17.44 15.  ]
 [56.55 44.9 ]
 [36.6  29.8 ]
 [27.91 23.6 ]
 [41.12 48.  ]
 [18.69 16.7 ]
 [41.19 40.9 ]
 [37.9  40.2 ]
 [16.36 12.9 ]
 [27.88 21.3 ]
 [48.76 62.1 ]
 [57.43 63.9 ]
 [36.12 40.3 ]
 [44.74 42.2 ]
 [16.58 19.1 ]
 [23.59 28.4 ]
 [35.64 28.5 ]
 [53.64 60.7 ]
 [39.93 37.5 ]
 [45.45 39.3 ]
 [25.24 28.8 ]
 [37.86 42.3 ]
 [40.6  44.3 ]
 [39.38 42.6 ]
 [51.43 57.4 ]
 [37.51 42.2 ]
 [22.79 25.7 ]
 [18.1  13

## Evaluating the Model Performance

In [ ]:
from sklearn.metrics import r2_score, mean_squared_error,mean_absolute_percentage_error
import math
maxY=max(y_test)
minY=min(y_test)
a=maxY-minY
print(a)
print ("The R-Squared value is: "+str(r2_score(y_test, y_pred)))
print ("The Mean Squared Error value is: "+str(mean_squared_error(y_test, y_pred)))
print ("The Root Mean Squared Error value is: "+str(math.sqrt(mean_squared_error(y_test, y_pred))))
print ("The Normalize Root Mean Squared Error value is: "+str(math.sqrt(mean_squared_error(y_test, y_pred))/(a[0])*100))
print ("The Mean Absolute Error value is: "+str(mean_absolute_percentage_error(y_test, y_pred)*100))

[65.4]
The R-Squared value is: 0.7044881583675278
The Mean Squared Error value is: 51.330115197479564
The Root Mean Squared Error value is: 7.164503834703389
The Normalize Root Mean Squared Error value is: 10.954898829821696
The Mean Absolute Error value is: 14.430131154033642
