# Random Forest Regression

Mounting a Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/RealEstateDataset.csv')
X = dataset.iloc[:, 1:7].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[2012.917     32.        84.87882   10.        24.98298  121.54024]
 [2012.917     19.5      306.5947     9.        24.98034  121.53951]
 [2013.583     13.3      561.9845     5.        24.98746  121.54391]
 ...
 [2013.25      18.8      390.9696     7.        24.97923  121.53986]
 [2013.         8.1      104.8101     5.        24.96674  121.54067]
 [2013.5        6.5       90.45606    9.        24.97433  121.5431 ]]
[ 37.9  42.2  47.3  54.8  43.1  32.1  40.3  46.7  18.8  22.1  41.4  58.1
  39.3  23.8  34.3  50.5  70.1  37.4  42.3  47.7  29.3  51.6  24.6  47.9
  38.8  27.   56.2  33.6  47.   57.1  22.1  25.   34.2  49.3  55.1  27.3
  22.9  25.3  47.7  46.2  15.9  18.2  34.7  34.1  53.9  38.3  42.   61.5
  13.4  13.2  44.2  20.7  27.   38.9  51.7  13.7  41.9  53.5  22.6  42.4
  21.3  63.2  27.7  55.   25.3  44.3  50.7  56.8  36.2  42.   59.   40.8
  36.3  20.   54.4  29.5  36.8  25.6  29.8  26.5  40.3  36.8  48.1  17.7
  43.7  50.8  27.   18.3  48.   25.3  45.4  43.2  21.8  16.1  41.   5

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Random Forest Regression model on the whole dataset

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

## Predicting the Test set results

In [ ]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[69.75 45.3 ]
 [15.79 14.4 ]
 [51.25 46.  ]
 [16.87 15.6 ]
 [33.32 50.2 ]
 [37.48 38.1 ]
 [41.3  48.5 ]
 [35.41 41.4 ]
 [63.32 51.6 ]
 [44.07 40.1 ]
 [40.99 42.  ]
 [18.83 42.4 ]
 [33.38 28.5 ]
 [43.36 39.1 ]
 [56.46 53.7 ]
 [48.87 36.8 ]
 [36.82 40.6 ]
 [48.98 55.2 ]
 [41.22 39.3 ]
 [44.81 44.3 ]
 [51.97 53.5 ]
 [27.58 25.3 ]
 [36.34 22.8 ]
 [53.24 51.7 ]
 [55.06 45.5 ]
 [40.91 34.4 ]
 [43.   31.6 ]
 [22.21 25.9 ]
 [53.58 49.5 ]
 [24.08 24.7 ]
 [44.82 51.7 ]
 [31.13 29.7 ]
 [50.05 45.4 ]
 [45.25 50.5 ]
 [41.07 26.5 ]
 [28.62 30.1 ]
 [44.5  46.1 ]
 [25.08 28.9 ]
 [54.15 54.4 ]
 [15.84 15.  ]
 [50.81 44.9 ]
 [36.51 29.8 ]
 [27.9  23.6 ]
 [49.37 48.  ]
 [17.11 16.7 ]
 [41.76 40.9 ]
 [39.57 40.2 ]
 [13.38 12.9 ]
 [26.18 21.3 ]
 [51.66 62.1 ]
 [59.95 63.9 ]
 [34.12 40.3 ]
 [50.51 42.2 ]
 [17.2  19.1 ]
 [27.34 28.4 ]
 [34.06 28.5 ]
 [55.68 60.7 ]
 [38.62 37.5 ]
 [39.54 39.3 ]
 [28.38 28.8 ]
 [41.11 42.3 ]
 [61.51 44.3 ]
 [41.01 42.6 ]
 [56.97 57.4 ]
 [40.41 42.2 ]
 [25.31 25.7 ]
 [15.53 13

## Evaluating the Model Performance

In [ ]:
from sklearn.metrics import r2_score, mean_squared_error,mean_absolute_percentage_error
import math
maxY=max(y_test)
minY=min(y_test)
a=maxY-minY
print(a)
print ("The R-Squared value is: "+str(r2_score(y_test, y_pred)))
print ("The Mean Squared Error value is: "+str(mean_squared_error(y_test, y_pred)))
print ("The Root Mean Squared Error value is: "+str(math.sqrt(mean_squared_error(y_test, y_pred))))
print ("The Normalize Root Mean Squared Error value is: "+str(math.sqrt(mean_squared_error(y_test, y_pred))/a*100))
print ("The Mean Absolute Error value is: "+str(mean_absolute_percentage_error(y_test, y_pred)*100))

65.39999999999999
The R-Squared value is: 0.6767353359686661
The Mean Squared Error value is: 56.150753053882205
The Root Mean Squared Error value is: 7.493380615842372
The Normalize Root Mean Squared Error value is: 11.457768525752863
The Mean Absolute Error value is: 13.431692575788038
