# Artificial Neural Network

### Importing the libraries

In [51]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Part 1 - Data Preprocessing

### Importing the dataset

In [52]:
dataset = pd.read_excel('Data.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

### Splitting the dataset into the Training set and Test set

In [53]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [54]:
print(X_train)
print(y_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]
[473.93 467.87 431.97 ... 459.01 462.72 428.12]


##Feature Scaling

In [55]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [56]:
print(y_train.reshape(-1,1))
print(y_test.reshape(-1,1))


[[473.93]
 [467.87]
 [431.97]
 ...
 [459.01]
 [462.72]
 [428.12]]
[[431.23]
 [460.01]
 [461.14]
 ...
 [473.26]
 [438.  ]
 [463.28]]


In [57]:
sc1 = StandardScaler()
y_train = sc1.fit_transform(y_train.reshape(-1,1))


## Part 2 - Building the ANN

### Initializing the ANN

In [58]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [59]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [60]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [61]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [62]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [63]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 2ms/step - loss: 0.2788
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 0.0893
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 0.0741
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 0.0696
Epoch 5/100
240/240 [==============================] - 0s 2ms/step - loss: 0.0676
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 0.0666
Epoch 7/100
240/240 [==============================] - 0s 2ms/step - loss: 0.0660
Epoch 8/100
240/240 [==============================] - 0s 2ms/step - loss: 0.0653
Epoch 9/100
240/240 [==============================] - 0s 2ms/step - loss: 0.0651
Epoch 10/100
240/240 [==============================] - 0s 2ms/step - loss: 0.0647
Epoch 11/100
240/240 [==============================] - 0s 2ms/step - loss: 0.0644
Epoch 12/100
240/240 [==============================] - 0s 2ms/step - loss: 0.0638
Epoch 13/100


### Predicting the results of the Test set

In [72]:
from sklearn.metrics import r2_score, mean_squared_error,mean_absolute_percentage_error
import math

y_pred = sc1.inverse_transform(ann.predict(X_test))
np.set_printoptions(precision=2)

maxY=max(y_test)
minY=min(y_test)
a=maxY-minY
print(a)

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
print ("The R-Squared value is: "+str(r2_score(y_test, y_pred)))
print ("The Mean Squared Error value is: "+str(mean_squared_error(y_test, y_pred)))
print ("The Root Mean Squared Error value is: "+str(math.sqrt(mean_squared_error(y_test, y_pred))))
print ("The Normalize Root Mean Squared Error value is: "+str(math.sqrt(mean_squared_error(y_test, y_pred))/(a)*100))
print ("The Mean Absolute Error value is: "+str(mean_absolute_percentage_error(y_test, y_pred)*100))


60/60 [==============================] - 0s 1ms/step
69.54999999999995
[[432.98 431.23]
 [458.33 460.01]
 [463.04 461.14]
 ...
 [468.26 473.26]
 [440.54 438.  ]
 [461.43 463.28]]
The R-Squared value is: 0.9450465922973981
The Mean Squared Error value is: 16.073203272412695
The Root Mean Squared Error value is: 4.009139966677728
The Normalize Root Mean Squared Error value is: 5.764399664525853
The Mean Absolute Error value is: 0.6970289734325141
